### ISSUE TITLE
aggregateFunc option of Field not working

### ISSUE THREAD

**Issue by ValentinH** [nnajm/orb#13]
Maybe I don't understand how to use it, but when I set aggregateFunc to 'avg' on a field using this syntax:
```js
{name: 'test', caption: 'Test', aggregateFunc: 'avg'}
```
The created field button displays "Test (avg)" if I place it in the data area, however the table is still using the sum aggregate.

In [the example](http://nnajm.github.io/orb/index.html), you use this syntax:

```js
{
      name: '6', caption: 'Amount',
      dataSettings: {
          aggregateFunc: 'avg',
          formatFunc: function(value) {
             return Number(value).toFixed(0);
          }
      }
}
```

and it does work.

What is the reason I can't use directly the aggregateFunc option?

**Comment by nnajm** [comment]
It's a bug :bug:...

**Comment by nnajm** [comment]
:thumbsup:
