### ISSUE TITLE
Use of custom aggregation function displays wrong name

### ISSUE THREAD

**Issue by ValentinH** [nnajm/orb#14]
If you set a custom aggregation in the aggregateFunc setting, the field still displays (sum) when dropped in the data area.

Indeed, when setting a custom function, I don't see currently any way to set this name. Maybe an aggregateFuncName option would be appreciable but I don't know if it is the best way to do it...

**Comment by nnajm** [comment]
`aggregateFuncName` already exists, it's just not documented. Sorry for that.

**Comment by ValentinH** [comment]
OK I understand. Indeed, I had seen `aggregateFuncName` in the code but I wasn't sure it was accessible from the config.

**Comment by nnajm** [comment]
:thumbsup:
