### ISSUE TITLE
Pivot table displays empty instead of zero by default

### ISSUE THREAD

**Issue by ValentinH** [nnajm/orb#16]
Is it on purpose that if I don't overwrite to formatFunc like in the example:
```js
formatFunc: function(value) {
   return Number(value).toFixed(0);
}
```
the cell displays a blank instead of 0?

**Comment by nnajm** [comment]
A blank cell means that no data was found for the target dimensions. If data exists and the result is 0, it should be displayed. Will fix it, it's a bug.

**Comment by nnajm** [comment]
:thumbsup:
