### ISSUE TITLE
JavaScript error when dataSource is an empty array

### ISSUE THREAD

**Issue by babyman** [nnajm/orb#23]
In version 1.0.8 if the dataSource is set to an empty array like so:

```javascript
var config = {
          dataSource: [],
          ...
```

Chrome registers a JS error "Uncaught TypeError: Cannot read property 'parent' of undefined".  My intent was to load the data via ajax in a separate call, my current workaround is to hardcode a single row of data with zeros and "Loading..." as its content, this seems to work for the time being.

Thanks for the great work =)

**Comment by nnajm** [comment]
:thumbsup:
