### ISSUE TITLE
Is possible to add calculated columns, like another "Grand Total"?

### ISSUE THREAD

**Issue by EduFrazao** [nnajm/orb#42]
Its possible to create another calculated column, like the Grand Total, but with a custom aggregate function?

I have this scenario:

_________Expected__Realized__Calculated_____Grand Total     (no even necessary in this case)
Row 1_______10_______5________50%____________15
Row 2_______20_______10_______50%____________30

How can I do such thing?
The Realized and Expected columns are only a column with a "descriptor" that I use to split records on columns.

**Comment by EduFrazao** [comment]
Problem solved. I added another Field, that not exists on datasource, with a custom aggregator, that reads the values of the intersection and produce the generated result:

```javascript
function(datafield, intersection, datasource, rowIndexes, colIndexes) {
    var somaOrcado = 0;
    var somaRealizado = 0;
    for (var i = 0; i < intersection.length; i++) {
        var row = datasource[intersection[i]];
        somaOrcado += row['ORCADO'];
        somaRealizado += row['REALIZADO'];
    }
    var percent = (somaRealizado * 100) / somaOrcado;
    return (percent) ? percent.toFixed(2) : 0.00;
}
```

**Comment by haozecc** [comment]
```javascript
function(datafield, intersection, datasource, rowIndexes, colIndexes) {
    var somaOrcado = 0;
    var somaRealizado = 0;
    for (var i = 0; i < intersection.length; i++) {
        var row = datasource[intersection[i]];
        somaOrcado += row['ORCADO'];
        somaRealizado += row['REALIZADO'];
    }
    var percent = (somaRealizado * 100) / somaOrcado;
    return (percent) ? percent.toFixed(2) : 0.00;
}
```
Can you tell me these code where you defined? options.fields? @EduFrazao
Thank you.

This is my code,but it's not valid.
```javascript
fields: [
  ...
  {
    name: null,
    caption: 'custom',
    aggregateFunc: function(datafield, intersection, datasource, rowIndexes, colIndexes) {
        return 111;
    }
  }
]
```

**Comment by EduFrazao** [comment]
Hi @haozecc .
I cant reproduce a 'Grand Total' like column, but with this code, I was wable to produce a entirely dynamic field, that can only appear on the data axis.

```
fields: [
   {
        name: 'a name',
        caption: 'Some Caption'
        dataSettings: {
              aggregateFunc: function(...) {...},
              aggregateFuncName: 'function name'
        } 
   }
]
```

I repeat, this field can only be used on the data axis. As Column or row, it not works, because it does not exists on datasource.
