### ISSUE TITLE
Using orb in Ember-Cli

### ISSUE THREAD

**Issue by mpujari** [nnajm/orb#63]
We are trying to use Orb in ember-cli but when we call below code

```
new orb.pgridwidget(config).render(document.getElementById('pgrid'));
````
OR
```
new orb.pgridwidget(config).render($('pgrid'));
````

Nothing gets displayed and there are no errors.

Note: In the template we do have a div with id 'pgrid'

Am we missing something?

**Comment by Zarkos69** [comment]
I think you might have forgotten to place # before pgrid ?

# for ID & . for Class

new orb.pgridwidget(config).render($('#pgrid'));

Maybe you could try (making an instance first, worked for me):
```
                        var elem = document.getElementById('pgrid');
                        $pivotTable = new orb.pgridwidget(config);
                        $pivotTable.render(elem);
```
