### ISSUE TITLE
Handle dynamic data changes

### ISSUE THREAD

**Issue by johnpletka** [nnajm/orb#9]
Is there a way to feed data changes into the datasource and have the aggregates recalculated?  I have a requirement to support data-changes over time.  If the control currently does not support it, could you point me in the right direction to add it?

Thanks

**Comment by nnajm** [comment]
Hello,

Sorry, it's not documented, but it's possible. You need a reference to the `orb.pgridwidget` instance, then call its [`refreshData`](http://nnajm.github.io/orb/documentation.html#Methods-refreshData) method with the new data source array. Sorting, filtering, collpsed states will be retained.

The website is now updated with this information.
